VERSION 0.6

FROM debian:stable-slim

hello:
    # using a patched vhs version to set no-sandbox go-rod option
    # could be replaced if https://github.com/charmbracelet/vhs/pull/195 is merged
    # maybe then also using the nix package works
    FROM ghcr.io/charmbracelet/vhs@sha256:018e10d9a61d7fe7e2fd76cfd3103211fc1a558d8c38d781bd2421fbe7230ac2
    RUN apt update && apt install -y cowsay
    # games is not part of PATH
    RUN mv /usr/games/cowsay /usr/local/bin
    # enable chromium no-sandbox
    ENV VHS_NO_SANDBOX="true"
    COPY greet-visitor.sh .
    COPY hello.tape .
    RUN vhs hello.tape
    SAVE ARTIFACT hello.gif AS LOCAL hello.gif

skyline:
    RUN apt update && apt install -y curl
    RUN echo $(( $(date +%Y)-1)) > last_year
    RUN curl -sSfLo skyline.svg "https://skylines.brumhard.com/brumhard/$(cat last_year)?type=svg"
    SAVE ARTIFACT skyline.svg AS LOCAL skyline.svg

# update-repo:
#     COPY --dir .git/ .
#     COPY +skyline/skyline.svg .
#     COPY +hello/hello.gif .
#     RUN git config user.email ""
#     RUN git config user.name ""
#     RUN git add skyline.svg hello.gif
#     RUN git commit -m "Update autogenerated files"
#     RUN git push